language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - postgresql

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-pychart
      - wkhtmltopdf
      - ttf-dejavu

install:
  - python bootstrap.py -v 2.5.3 --setuptools-version=29.0.1
  - bin/buildout -c buildout-travis.cfg
  - createdb zitcom
  - psql zitcom -c "create extension postgis;"
  - bin/upgrade_odoo -d zitcom --init-load-demo-data

script:
  - bin/nosetests -d zitcom -- -v modules/
